include: package:flutter_lints/flutter.yaml

formatter:
  trailing_commas: preserve

linter:
  rules:
    avoid_print: false
    prefer_single_quotes: true
    require_trailing_commas: true
    always_put_required_named_parameters_first: true
